# Generated by Django 3.1.6 on 2021-05-01 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='test', upload_to='category'),
            preserve_default=False,
        ),
    ]
