# Generated by Django 3.1.6 on 2021-05-10 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0005_auto_20210510_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='notification',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='coupon.notification'),
        ),
    ]
