# Generated by Django 3.1.6 on 2021-05-10 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0007_auto_20210510_0553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='notification',
        ),
        migrations.AddField(
            model_name='message',
            name='notification',
            field=models.ManyToManyField(to='coupon.Notification'),
        ),
    ]
