# Generated by Django 3.1.6 on 2021-05-10 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0008_auto_20210510_0705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
    ]
