# Generated by Django 3.1.6 on 2021-05-12 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0009_remove_message_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name_plural': 'Notifications'},
        ),
    ]
