# Generated by Django 3.1.6 on 2021-06-03 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0010_auto_20210512_0424'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='sms',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
